const reasons = [
    "Porque tu sonrisa ilumina mi día",
    "Porque haces que hasta lo simple se sienta mágico",
    "Porque me haces querer ser una mejor persona",
    "Porque no necesito esconder ninguna parte de mí cuando estoy contigo",
    "Porque tienes esa forma de mirarme que me calma",
    "Porque me haces sentir elegida todos los días",
    "Porque tu risa es mi sonido favorito",
    "Porque hasta tus enojos me gustan",
    "Porque me muestras tu amor",
    "Porque me escuchás incluso cuando no sé cómo decir las cosas",
    "Porque incluso a kilómetros de distancia, lográs hacerme sentir cerca",
    "Porque tienes una forma única de ver el mundo y me encanta aprender de ti",
    "Porque amarte se siente natural",
    "Porque me das ganas de construir futuro",
    "Porque eres refugio y aventura al mismo tiempo",
    "Porque esperar por ti tiene sentido",
    "Porque no importa cuánto tiempo pase, siempre siento que estás cerca",
    "Porque eres mi lugar seguro",
    "Porque nunca me había sentido tan en casa con alguien",
    "Porque nuestras diferencias también suman",
    "Porque el tiempo que pasamos separadas solo hace que valore más cada momento juntas",
    "Porque me haces sentir vista",
    "Porque contigo aprendí a amar mejor",
    "Porque cada día que pasa, me doy cuenta de lo afortunada que soy por tenerte",
    "Porque tu forma de amar es suave y fuerte a la vez",
    "Porque te admiro, no solo te amo",
    "Porque me haces reír en los momentos más inesperados",
    "Porque confiás en mí",
    "Porque nuestros planes a futuro me llenan de esperanza",
    "Porque no todo es perfecto, pero lo enfrentamos juntas",
    "Porque me haces sentir deseada sin decir una palabra",
    "Porque cada día sin verte me recuerda lo mucho que te extraño",
    "Porque tus abrazos me curan cualquier cosa",
    "Porque nuestras conversaciones a cualquier hora me hacen feliz",
    "Porque tu amor no es condición, es decisión",
    "Porque me das ganas de crecer, no de huir",
    "Porque tienes el humor bien agrio como yo",
    "Porque me enseñás a ser mejor cada día",
    "Porque me siento libre",
    "Porque me haces sentir orgullosa de lo que somos",
    "Porque confiás en mí",
    "Porque me dejás ser parte de tu mundo",
    "Porque cuando te veo, me enamoro más",
    "Porque no necesito filtros con vos",
    "Porque nuestras diferencias también nos unen",
    "Porque me haces sentir elegida",
    "Porque tieness esa energía que me levanta el ánimo",
    "Porque me haces sentir valiente",
    "Porque te importa lo que siento de verdad",
    "Porque sabés disfrutar lo simple sin quejarte",
    "Porque me acompañás sin invadir",
    "Porque me inspiras todos los días, sin darte cuenta",
    "Porque cuando me besas siento que te necesito más",
    "Porque no hay nadie con quien prefiera compartir la vida",
    "Porque somos equipo en lo bueno y en lo malo",
    "Porque puedes ser dulce y enojona, y eso me encanta",
    "Porque todo es más lindo cuando estás",
    "Porque te siento incluso cuando no estás cerca",
    "Porque aprendí que amar también es cuidar y respetar",
    "Porque amarte se ha convertido en mi deporte favorito"
  ];
  